server:
  port: 7788
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3336/dpt?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: daoying
    driver-class-name: com.mysql.cj.jdbc.Driver
